/*
 * Copyright (C) 1999-2001  Brian Paul   All Rights Reserved.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * BRIAN PAUL BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/*
 * Ported to GLES2.
 * Kristian Høgsberg <krh@bitplanet.net>
 * May 3, 2010
 * 
 * Improve GLES2 port:
 *   * Refactor gear drawing.
 *   * Use correct normals for surfaces.
 *   * Improve shader.
 *   * Use perspective projection transformation.
 *   * Add FPS count.
 *   * Add comments.
 * Alexandros Frantzis <alexandros.frantzis@linaro.org>
 * Jul 13, 2010
 */
/* 
 * Asked Gemini3 port to pure wayland.
 * Port to wayland generated by Gemini3
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <sys/time.h>
#include <unistd.h>
#include <linux/input.h>

#include <wayland-client.h>
#include <wayland-egl.h>
#include <EGL/egl.h>
#include <EGL/eglext.h>
#include <GLES2/gl2.h>

#include "xdg-shell-protocol.h"

/* Ported math/rendering structures from es2gears.c */
#define STRIPS_PER_TOOTH 7
#define VERTICES_PER_TOOTH 34
#define GEAR_VERTEX_STRIDE 6

struct vertex_strip {
   GLint first;
   GLint count;
};

typedef GLfloat GearVertex[GEAR_VERTEX_STRIDE];

struct gear {
   GearVertex *vertices;
   int nvertices;
   struct vertex_strip *strips;
   int nstrips;
   GLuint vbo;
};

/* Wayland and EGL state */
struct display {
    struct wl_display *display;
    struct wl_registry *registry;
    struct wl_compositor *compositor;
    struct xdg_wm_base *xdg_wm_base;
    struct wl_seat *seat;
    struct wl_pointer *pointer;
    struct wl_keyboard *keyboard;
    struct {
        EGLDisplay dpy;
        EGLContext ctx;
        EGLConfig conf;
    } egl;
};

struct window {
    struct display *display;
    struct wl_surface *surface;
    struct xdg_surface *xdg_surface;
    struct xdg_toplevel *xdg_toplevel;
    struct wl_egl_window *native;
    EGLSurface egl_surface;
    int width, height; // Content size
    int configured;
    float pointer_x, pointer_y;
    uint32_t button_serial;
};

/** The view rotation [x, y, z] */
static GLfloat view_rot[3] = { 20.0, 30.0, 0.0 };
static int fullscreen = 0;
static int print_info = 0;
/** The gears */
static struct gear *gear1, *gear2, *gear3;
/** The current gear rotation angle */
static GLfloat angle = 0.0;
/** The location of the shader uniforms */
static GLuint ModelViewProjectionMatrix_location,
              NormalMatrix_location,
              LightSourcePosition_location,
              MaterialColor_location;
/** The projection matrix */
static GLfloat ProjectionMatrix[16];
/** The direction of the directional light for the scene */
static const GLfloat LightSourcePosition[4] = { 5.0, 5.0, 10.0, 1.0};
/** Title bar height in pixels */
static const int TITLE_BAR_HEIGHT = 28;

/* --- Math Utilities (Ported from es2gears.c) --- */

/**
 * Calculates sine and cosine of an angle.
 *
 * @param a angle in radians
 * @param s pointer to store sine
 * @param c pointer to store cosine
 */
static void
sincos(double a, double *s, double *c)
{
    *s = sin(a);
    *c = cos(a);
}

/**
 * Creates an identity 4x4 matrix.
 *
 * @param m the matrix make an identity matrix
 */
static void
identity(GLfloat *m)
{
    static const GLfloat t[16] = { 1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1 };
    memcpy(m, t, sizeof(t));
}

/**
 * Multiplies two 4x4 matrices.
 *
 * The result is stored in matrix m.
 *
 * @param m the first matrix to multiply
 * @param n the second matrix to multiply
 */
static void
multiply(GLfloat *m, const GLfloat *n)
{
    GLfloat tmp[16];
    for (int i = 0; i < 4; i++) {
        for (int j = 0; j < 4; j++) {
            tmp[i * 4 + j] = 0.0;
            for (int k = 0; k < 4; k++)
                tmp[i * 4 + j] += n[i * 4 + k] * m[k * 4 + j];
        }
    }
    memcpy(m, tmp, sizeof(tmp));
}

/**
 * Rotates a 4x4 matrix.
 *
 * @param[in,out] m the matrix to rotate
 * @param angle the angle to rotate
 * @param x the x component of the direction to rotate to
 * @param y the y component of the direction to rotate to
 * @param z the z component of the direction to rotate to
 */
static void
rotate(GLfloat *m, GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
{
    double s, c;
    sincos(angle, &s, &c);
    GLfloat r[16] = {
        x * x * (1 - c) + c,     y * x * (1 - c) + z * s, x * z * (1 - c) - y * s, 0,
        x * y * (1 - c) - z * s, y * y * (1 - c) + c,     y * z * (1 - c) + x * s, 0,
        x * z * (1 - c) + y * s, y * z * (1 - c) - x * s, z * z * (1 - c) + c,     0,
        0, 0, 0, 1
    };
    multiply(m, r);
}

/**
 * Translates a 4x4 matrix.
 *
 * @param[in,out] m the matrix to translate
 * @param x the x component of the direction to translate to
 * @param y the y component of the direction to translate to
 * @param z the z component of the direction to translate to
 */
static void
translate(GLfloat *m, GLfloat x, GLfloat y, GLfloat z)
{
    GLfloat t[16] = { 1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  x, y, z, 1 };
    multiply(m, t);
}

/**
 * Transposes a 4x4 matrix.
 *
 * @param m the matrix to transpose
 */
static void
transpose(GLfloat *m)
{
    GLfloat t[16] = { m[0],m[4],m[8],m[12], m[1],m[5],m[9],m[13], m[2],m[6],m[10],m[14], m[3],m[7],m[11],m[15] };
    memcpy(m, t, sizeof(t));
}

/**
 * Inverts a 4x4 matrix.
 *
 * This function can currently handle only pure translation-rotation matrices.
 */
static void
invert(GLfloat *m)
{
    GLfloat t[16]; identity(t);
    t[12] = -m[12]; t[13] = -m[13]; t[14] = -m[14];
    m[12] = m[13] = m[14] = 0;
    transpose(m);
    multiply(m, t);
}

/**
 * Calculate a perspective projection transformation.
 *
 * @param m the matrix to save the transformation in
 * @param fovy the field of view in the y direction
 * @param aspect the view aspect ratio
 * @param zNear the near clipping plane
 * @param zFar the far clipping plane
 */
static void
perspective(GLfloat *m, GLfloat fovy, GLfloat aspect, GLfloat zNear, GLfloat zFar)
{
    GLfloat tmp[16]; identity(tmp);
    double sine, cosine, cotangent, deltaZ;
    GLfloat radians = fovy / 2 * M_PI / 180;
    deltaZ = zFar - zNear;
    sincos(radians, &sine, &cosine);
    if (deltaZ == 0 || sine == 0 || aspect == 0) return;
    cotangent = cosine / sine;
    tmp[0] = cotangent / aspect; tmp[5] = cotangent;
    tmp[10] = -(zFar + zNear) / deltaZ; tmp[11] = -1;
    tmp[14] = -2 * zNear * zFar / deltaZ; tmp[15] = 0;
    memcpy(m, tmp, sizeof(tmp));
}

/* --- Gear Generation (Ported from es2gears.c) --- */

/**
 * Fills a gear vertex.
 *
 * @param v the vertex to fill
 * @param x the x coordinate
 * @param y the y coordinate
 * @param z the z coordinate
 * @param n pointer to the normal table
 *
 * @return the pointer to the next vertex
 */
static GearVertex *
vert(GearVertex *v, GLfloat x, GLfloat y, GLfloat z, GLfloat n[3])
{
   v[0][0] = x;
   v[0][1] = y;
   v[0][2] = z;
   v[0][3] = n[0];
   v[0][4] = n[1];
   v[0][5] = n[2];
   return v + 1;
}

/**
 * Create a gear wheel.
 *
 * @param inner_radius radius of hole at center
 * @param outer_radius radius at center of teeth
 * @param width width of gear
 * @param teeth number of teeth
 * @param tooth_depth depth of tooth
 *
 * @return pointer to the constructed struct gear
 */
static struct gear *create_gear(GLfloat inner_radius, GLfloat outer_radius, GLfloat width, GLint teeth, GLfloat tooth_depth) {
   GLfloat r0, r1, r2, da, normal[3];
   GearVertex *v;
   struct gear *gear = malloc(sizeof *gear);
   double s[5], c[5];
   int cur_strip = 0;

   r0 = inner_radius;
   r1 = outer_radius - tooth_depth / 2.0;
   r2 = outer_radius + tooth_depth / 2.0;

   da = 2.0 * M_PI / teeth / 4.0;
   gear->nstrips = STRIPS_PER_TOOTH * teeth;
   gear->strips = calloc(gear->nstrips, sizeof (*gear->strips));
   gear->vertices = calloc(VERTICES_PER_TOOTH * teeth, sizeof(*gear->vertices));
   v = gear->vertices;

   for (int i = 0; i < teeth; i++) {
      for (int j = 0; j < 5; j++)
         sincos(i * 2.0 * M_PI / teeth + da * j, &s[j], &c[j]);

      struct { GLfloat x, y; } p[7] = {
         {r2 * c[1], r2 * s[1]},
         {r2 * c[2], r2 * s[2]},
         {r1 * c[0], r1 * s[0]},
         {r1 * c[3], r1 * s[3]},
         {r0 * c[0], r0 * s[0]},
         {r1 * c[4], r1 * s[4]},
         {r0 * c[4], r0 * s[4]}
      };

      #define START_STRIP \
         gear->strips[cur_strip].first = v - gear->vertices

      #define END_STRIP \
         do { \
            int _tmp = (v - gear->vertices); \
            gear->strips[cur_strip].count = _tmp - gear->strips[cur_strip].first; \
            cur_strip++; \
         } while (0)

      #define SET_NORM(x, y, z) \
         do { \
            normal[0] = (x); \
            normal[1] = (y); \
            normal[2] = (z); \
         } while (0)

      #define V(idx, sign) \
         v = vert(v, p[idx].x, p[idx].y, (sign) * width * 0.5, normal)

      /* Front face */
      START_STRIP;
      SET_NORM(0, 0, 1.0);
      V(0, 1);
      V(1, 1);
      V(2, 1);
      V(3, 1);
      V(4, 1);
      V(5, 1);
      V(6, 1);
      END_STRIP;

      /* Inner face */
      START_STRIP;
      SET_NORM(p[4].y - p[6].y, -(p[4].x - p[6].x), 0);
      V(4, -1);
      V(4, 1);
      V(6, -1);
      V(6, 1);
      END_STRIP;

      /* Back face */
      START_STRIP;
      SET_NORM(0, 0, -1.0);
      V(6, -1);
      V(5, -1);
      V(4, -1);
      V(3, -1);
      V(2, -1);
      V(1, -1);
      V(0, -1);
      END_STRIP;

      /* Outer face */
      START_STRIP;
      SET_NORM(p[0].y - p[2].y, -(p[0].x - p[2].x), 0);
      V(0, -1);
      V(0, 1);
      V(2, -1);
      V(2, 1);
      END_STRIP;

      START_STRIP;
      SET_NORM(p[1].y - p[0].y, -(p[1].x - p[0].x), 0);
      V(1, -1);
      V(1, 1);
      V(0, -1);
      V(0, 1);
      END_STRIP;

      START_STRIP;
      SET_NORM(p[3].y - p[1].y, -(p[3].x - p[1].x), 0);
      V(3, -1);
      V(3, 1);
      V(1, -1);
      V(1, 1);
      END_STRIP;

      START_STRIP;
      SET_NORM(p[5].y - p[3].y, -(p[5].x - p[3].x), 0);
      V(5, -1);
      V(5, 1);
      V(3, -1);
      V(3, 1);
      END_STRIP;
   }
   gear->nvertices = (v - gear->vertices);
   glGenBuffers(1, &gear->vbo);
   glBindBuffer(GL_ARRAY_BUFFER, gear->vbo);
   glBufferData(GL_ARRAY_BUFFER, gear->nvertices * sizeof(GearVertex), gear->vertices, GL_STATIC_DRAW);
   return gear;
}

/* --- Rendering logic --- */

/**
 * Draws a gear.
 *
 * @param gear the gear to draw
 * @param transform the current transformation matrix
 * @param x the x position to draw the gear at
 * @param y the y position to draw the gear at
 * @param angle the rotation angle of the gear
 * @param color the color of the gear
 */
static void
draw_gear(struct gear *gear, GLfloat *transform, GLfloat x, GLfloat y, GLfloat angle, const GLfloat color[4])
{
   GLfloat mv[16], nm[16], mvp[16];
   memcpy(mv, transform, sizeof(mv));
   translate(mv, x, y, 0);
   rotate(mv, 2 * M_PI * angle / 360.0, 0, 0, 1);
   memcpy(mvp, ProjectionMatrix, sizeof(mvp));
   multiply(mvp, mv);
   glUniformMatrix4fv(ModelViewProjectionMatrix_location, 1, GL_FALSE, mvp);

   memcpy(nm, mv, sizeof(nm));
   invert(nm);
   transpose(nm);
   glUniformMatrix4fv(NormalMatrix_location, 1, GL_FALSE, nm);

   glUniform4fv(MaterialColor_location, 1, color);
   glBindBuffer(GL_ARRAY_BUFFER, gear->vbo);
   glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 6 * sizeof(GLfloat), NULL);
   glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, 6 * sizeof(GLfloat), (GLfloat *) 0 + 3);

   glEnableVertexAttribArray(0);
   glEnableVertexAttribArray(1);

   for (int n = 0; n < gear->nstrips; n++)
      glDrawArrays(GL_TRIANGLE_STRIP, gear->strips[n].first, gear->strips[n].count);
}

/**
 * Redraws the scene.
 *
 * @param window the window to redraw
 */
static void redraw(struct window *window) {
    const static GLfloat red[4] = { 0.8, 0.1, 0.0, 1.0 }, green[4] = { 0.0, 0.8, 0.2, 1.0 }, blue[4] = { 0.2, 0.2, 1.0, 1.0 };
    GLfloat transform[16]; identity(transform);

    int total_h = window->height + (fullscreen ? 0 : TITLE_BAR_HEIGHT);

    glClearColor(0.0, 0.0, 0.0, 1.0);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

    /* Draw a simple grey title bar if not fullscreen */
    if (!fullscreen) {
        glEnable(GL_SCISSOR_TEST);
        glScissor(0, window->height, window->width, TITLE_BAR_HEIGHT);
        glClearColor(0.3, 0.3, 0.3, 1.0);
        glClear(GL_COLOR_BUFFER_BIT);
        glDisable(GL_SCISSOR_TEST);
    }

    /* Set viewport to the content area below the title bar */
    glViewport(0, 0, window->width, window->height);

    translate(transform, 0, 0, -20);
    rotate(transform, 2 * M_PI * view_rot[0] / 360.0, 1, 0, 0);
    rotate(transform, 2 * M_PI * view_rot[1] / 360.0, 0, 1, 0);
    rotate(transform, 2 * M_PI * view_rot[2] / 360.0, 0, 0, 1);

    draw_gear(gear1, transform, -3.0, -2.0, angle, red);
    draw_gear(gear2, transform, 3.1, -2.0, -2 * angle - 9.0, green);
    draw_gear(gear3, transform, -3.1, 4.2, -2 * angle - 25.0, blue);

    eglSwapBuffers(window->display->egl.dpy, window->egl_surface);
}


/* --- Wayland / EGL Plumbing --- */

static void
keyboard_handle_keymap(void *data, struct wl_keyboard *keyboard,
                      uint32_t format, int fd, uint32_t size)
{
    close(fd);
}

static void
keyboard_handle_enter(void *data, struct wl_keyboard *keyboard,
                      uint32_t serial, struct wl_surface *surface,
                      struct wl_array *keys) {}

static void
keyboard_handle_leave(void *data, struct wl_keyboard *keyboard,
                      uint32_t serial, struct wl_surface *surface) {}

static void
keyboard_handle_key(void *data, struct wl_keyboard *keyboard,
                    uint32_t serial, uint32_t time, uint32_t key,
                    uint32_t state)
{
    if (state != WL_KEYBOARD_KEY_STATE_PRESSED) return;

    switch (key) {
        case KEY_Q:
            exit(0);
            break;
        case KEY_LEFT:
            view_rot[1] += 5.0;
            break;
        case KEY_RIGHT:
            view_rot[1] -= 5.0;
            break;
        case KEY_UP:
            view_rot[0] += 5.0;
            break;
        case KEY_DOWN:
            view_rot[0] -= 5.0;
            break;
    }
}

static void
keyboard_handle_modifiers(void *data, struct wl_keyboard *keyboard,
                          uint32_t serial, uint32_t mods_depressed,
                          uint32_t mods_latched, uint32_t mods_locked,
                          uint32_t group) {}

static const struct wl_keyboard_listener keyboard_listener = {
    keyboard_handle_keymap, keyboard_handle_enter, keyboard_handle_leave,
    keyboard_handle_key, keyboard_handle_modifiers
};

static void
pointer_handle_enter(void *data, struct wl_pointer *pointer, uint32_t serial,
                    struct wl_surface *surface, wl_fixed_t sx, wl_fixed_t sy) {}

static void
pointer_handle_leave(void *data, struct wl_pointer *pointer, uint32_t serial,
                    struct wl_surface *surface) {}

static void
pointer_handle_motion(void *data, struct wl_pointer *pointer, uint32_t time,
                     wl_fixed_t sx, wl_fixed_t sy)
{
    struct display *d = data;
    /* Note: In a real app, you'd find which window the pointer is in. 
       For this demo, we assume the main window. */
}

static void
pointer_handle_button(void *data, struct wl_pointer *pointer, uint32_t serial,
                     uint32_t time, uint32_t button, uint32_t state)
{
    struct display *d = data;
    /* For move, we need to know if the click was in the 'title bar' area.
       Since we don't have the pointer coordinates saved in a sophisticated way here,
       we'll just use a simple heuristic or state tracking if needed. */
    if (button == BTN_LEFT && state == WL_POINTER_BUTTON_STATE_PRESSED) {
        /* We can call move here. Compositors usually handle the 'interactive' move. */
        /* In a full CSD implementation, you'd check: if (y < TITLE_BAR_HEIGHT) */
    }
}

static void
pointer_handle_axis(void *data, struct wl_pointer *pointer, uint32_t time,
                   uint32_t axis, wl_fixed_t value) {}

static const struct wl_pointer_listener pointer_listener = {
    pointer_handle_enter, pointer_handle_leave, pointer_handle_motion,
    pointer_handle_button, pointer_handle_axis
};

static void
seat_handle_capabilities(void *data, struct wl_seat *seat,
                         uint32_t caps)
{
    struct display *d = data;
    if ((caps & WL_SEAT_CAPABILITY_POINTER) && !d->pointer) {
        d->pointer = wl_seat_get_pointer(seat);
        wl_pointer_add_listener(d->pointer, &pointer_listener, d);
    } else if (!(caps & WL_SEAT_CAPABILITY_POINTER) && d->pointer) {
        wl_pointer_destroy(d->pointer);
        d->pointer = NULL;
    }

    if ((caps & WL_SEAT_CAPABILITY_KEYBOARD) && !d->keyboard) {
        d->keyboard = wl_seat_get_keyboard(seat);
        wl_keyboard_add_listener(d->keyboard, &keyboard_listener, d);
    } else if (!(caps & WL_SEAT_CAPABILITY_KEYBOARD) && d->keyboard) {
        wl_keyboard_destroy(d->keyboard);
        d->keyboard = NULL;
    }
}

static void
seat_handle_name(void *data, struct wl_seat *seat, const char *name) {}

static const struct wl_seat_listener seat_listener = {
    seat_handle_capabilities, seat_handle_name
};

/**
 * Handles xdg_toplevel configure events.
 *
 * @param data pointer to struct window
 * @param xdg_toplevel the toplevel object
 * @param width the new width
 * @param height the new height
 * @param states array of window states
 */
static void xdg_toplevel_handle_configure(void *data, struct xdg_toplevel *xdg_toplevel, int32_t width, int32_t height, struct wl_array *states) {
    struct window *window = data;
    if (width > 0 && height > 0) {
        /* The compositor gives us the 'window geometry' size. 
           If we are doing CSD, our buffer must be larger than this to include title bars,
           OR we subtract the title bar from the allocation. */
        window->width = width;
        window->height = height - (fullscreen ? 0 : TITLE_BAR_HEIGHT);
    }
}


/**
 * Handles xdg_toplevel close events.
 *
 * @param data pointer to struct window
 * @param xdg_toplevel the toplevel object
 */
static void xdg_toplevel_handle_close(void *data, struct xdg_toplevel *xdg_toplevel) {
    exit(0);
}

static const struct xdg_toplevel_listener xdg_toplevel_listener = {
   xdg_toplevel_handle_configure,
   xdg_toplevel_handle_close
};

/**
 * Handles xdg_surface configure events.
 *
 * @param data pointer to struct window
 * @param xdg_surface the surface object
 * @param serial the configure serial
 */
static void xdg_surface_handle_configure(void *data, struct xdg_surface *xdg_surface, uint32_t serial) {
    struct window *window = data;
    xdg_surface_ack_configure(xdg_surface, serial);
    
    int buffer_width = window->width;
    int buffer_height = window->height + (fullscreen ? 0 : TITLE_BAR_HEIGHT);

    if (window->native) wl_egl_window_resize(window->native, buffer_width, buffer_height, 0, 0);

    xdg_surface_set_window_geometry(xdg_surface, 0, 0, window->width, buffer_height);
    perspective(ProjectionMatrix, 60.0, (float)window->width / (float)window->height, 1.0, 1024.0);
    window->configured = 1;
}

static const struct xdg_surface_listener xdg_surface_listener = {
   xdg_surface_handle_configure
};


/**
 * Responds to xdg_wm_base ping events.
 *
 * @param data pointer to struct display
 * @param xdg_wm_base the shell object
 * @param serial the ping serial
 */
static void xdg_wm_base_ping(void *data, struct xdg_wm_base *xdg_wm_base, uint32_t serial) {
    xdg_wm_base_pong(xdg_wm_base, serial);
}

static const struct xdg_wm_base_listener xdg_wm_base_listener = {
   xdg_wm_base_ping
};


/**
 * Handles registry global events to bind necessary interfaces.
 *
 * @param data pointer to struct display
 * @param registry the registry object
 * @param id global object id
 * @param interface interface name
 * @param version interface version
 */
static void
registry_handle_global(void *data, struct wl_registry *registry, uint32_t id, const char *interface, uint32_t version)
{
    struct display *d = data;
    if (strcmp(interface, "wl_compositor") == 0) d->compositor = wl_registry_bind(registry, id, &wl_compositor_interface, 1);
    else if (strcmp(interface, "xdg_wm_base") == 0) {
        d->xdg_wm_base = wl_registry_bind(registry, id, &xdg_wm_base_interface, 1);
        xdg_wm_base_add_listener(d->xdg_wm_base, &xdg_wm_base_listener, d);
    }
    else if (strcmp(interface, "wl_seat") == 0) {
        d->seat = wl_registry_bind(registry, id, &wl_seat_interface, 1);
        wl_seat_add_listener(d->seat, &seat_listener, d);
    }
}

/**
 * Handles registry global removal events.
 *
 * @param data pointer to struct display
 * @param registry the registry object
 * @param id global object id
 */
static void registry_handle_global_remove(void *data, struct wl_registry *registry, uint32_t id) {}

static const struct wl_registry_listener registry_listener = {
   registry_handle_global,
   registry_handle_global_remove
};


/**
 * Initializes EGL and creates a context.
 *
 * @param display the display object
 */
static void
init_egl(struct display *display)
{
    EGLint major, minor, n;
    static const EGLint argb_cfg[] = { EGL_RENDERABLE_TYPE, EGL_OPENGL_ES2_BIT, EGL_SURFACE_TYPE, EGL_WINDOW_BIT, EGL_RED_SIZE, 1, EGL_GREEN_SIZE, 1, EGL_BLUE_SIZE, 1, EGL_ALPHA_SIZE, 1, EGL_DEPTH_SIZE, 1, EGL_NONE };
    static const EGLint ctx_attribs[] = { EGL_CONTEXT_CLIENT_VERSION, 2, EGL_NONE };

    display->egl.dpy = eglGetDisplay((EGLNativeDisplayType)display->display);
    eglInitialize(display->egl.dpy, &major, &minor);

    printf("EGL_VERSION = %s\n", eglQueryString(display->egl.dpy, EGL_VERSION));

    eglBindAPI(EGL_OPENGL_ES_API);
    eglChooseConfig(display->egl.dpy, argb_cfg, &display->egl.conf, 1, &n);
    display->egl.ctx = eglCreateContext(display->egl.dpy, display->egl.conf, EGL_NO_CONTEXT, ctx_attribs);
}

/**
 * Creates a Wayland surface and binds it to EGL.
 *
 * @param window the window object
 */
static void
create_window(struct window *window)
{
    window->surface = wl_compositor_create_surface(window->display->compositor);
    window->xdg_surface = xdg_wm_base_get_xdg_surface(window->display->xdg_wm_base, window->surface);
    xdg_surface_add_listener(window->xdg_surface, &xdg_surface_listener, window);
    window->xdg_toplevel = xdg_surface_get_toplevel(window->xdg_surface);
    xdg_toplevel_add_listener(window->xdg_toplevel, &xdg_toplevel_listener, window);
    xdg_toplevel_set_title(window->xdg_toplevel, "Wayland EGL Gears");
    if (fullscreen) xdg_toplevel_set_fullscreen(window->xdg_toplevel, NULL);
    wl_surface_commit(window->surface);

    window->native = wl_egl_window_create(window->surface, window->width, window->height);
    window->egl_surface = eglCreateWindowSurface(window->display->egl.dpy, window->display->egl.conf, (EGLNativeWindowType)window->native, NULL);
    eglMakeCurrent(window->display->egl.dpy, window->egl_surface, window->egl_surface, window->display->egl.ctx);
}

/**
 * Initializes OpenGL ES 2 state, compiles shaders, and creates gears.
 */
static void
init_gl()
{
    const char *vertex_shader =
"attribute vec3 position;\n"
"attribute vec3 normal;\n"
"\n"
"uniform mat4 ModelViewProjectionMatrix;\n"
"uniform mat4 NormalMatrix;\n"
"uniform vec4 LightSourcePosition;\n"
"uniform vec4 MaterialColor;\n"
"\n"
"varying vec4 Color;\n"
"\n"
"void main(void)\n"
"{\n"
"    // Transform the normal to eye coordinates\n"
"    vec3 N = normalize(vec3(NormalMatrix * vec4(normal, 1.0)));\n"
"\n"
"    // The LightSourcePosition is actually its direction for directional light\n"
"    vec3 L = normalize(LightSourcePosition.xyz);\n"
"\n"
"    // Multiply the diffuse value by the vertex color (which is fixed in this case)\n"
"    // to get the actual color that we will use to draw this vertex with\n"
"    float diffuse = max(dot(N, L), 0.0);\n"
"    Color = diffuse * MaterialColor;\n"
"\n"
"    // Transform the position to clip coordinates\n"
"    gl_Position = ModelViewProjectionMatrix * vec4(position, 1.0);\n"
"}";

    const char *fragment_shader =
"#ifdef GL_ES\n"
"precision mediump float;\n"
"#endif\n"
"varying vec4 Color;\n"
"\n"
"void main(void)\n"
"{\n"
"    gl_FragColor = Color;\n"
"}";

    GLuint v = glCreateShader(GL_VERTEX_SHADER);
    glShaderSource(v, 1, &vertex_shader, NULL);
    glCompileShader(v);

    GLuint f = glCreateShader(GL_FRAGMENT_SHADER);
    glShaderSource(f, 1, &fragment_shader, NULL);
    glCompileShader(f);

    GLuint prog = glCreateProgram();
    glAttachShader(prog, v);
    glAttachShader(prog, f);
    glBindAttribLocation(prog, 0, "position");
    glBindAttribLocation(prog, 1, "normal");

    glLinkProgram(prog);
    glUseProgram(prog);

    if (print_info) {
        printf("GL_RENDERER   = %s\n", (char *) glGetString(GL_RENDERER));
        printf("GL_VERSION    = %s\n", (char *) glGetString(GL_VERSION));
        printf("GL_VENDOR     = %s\n", (char *) glGetString(GL_VENDOR));
    }

    ModelViewProjectionMatrix_location = glGetUniformLocation(prog, "ModelViewProjectionMatrix");
    NormalMatrix_location = glGetUniformLocation(prog, "NormalMatrix");
    LightSourcePosition_location = glGetUniformLocation(prog, "LightSourcePosition");
    MaterialColor_location = glGetUniformLocation(prog, "MaterialColor");
    glUniform4fv(LightSourcePosition_location, 1, LightSourcePosition);
    glEnable(GL_CULL_FACE); glEnable(GL_DEPTH_TEST);
    gear1 = create_gear(1.0, 4.0, 1.0, 20, 0.7);
    gear2 = create_gear(0.5, 2.0, 2.0, 10, 0.7);
    gear3 = create_gear(1.3, 2.0, 0.5, 10, 0.7);
}

static void
usage(const char *name)
{
    printf("Usage: %s [options]\n", name);
    printf("Options:\n");
    printf("  -wayland <name>  Wayland display name\n");
    printf("  -info            Show OpenGL info\n");
    printf("  -fullscreen      Run in fullscreen mode\n");
    printf("  --help           Show this help\n");
}

/**
 * Main entry point for the Wayland GLES2 gears demo.
 *
 * @param argc argument count
 * @param argv argument vector
 * @return exit status
 */
int
main(int argc, char **argv)
{
    struct display display = {0};
    struct window window = { .display = &display, .width = 300, .height = 300 };
    char *wayland_name = NULL;

    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-wayland") == 0 && i + 1 < argc) {
            wayland_name = argv[++i];
        } else if (strcmp(argv[i], "-info") == 0) {
            print_info = 1;
        } else if (strcmp(argv[i], "-fullscreen") == 0) {
            fullscreen = 1;
        } else if (strcmp(argv[i], "--help") == 0) {
            usage(argv[0]);
            return 0;
        } else {
            usage(argv[0]);
            return -1;
        }
    }

    display.display = wl_display_connect(wayland_name);
    if (display.display == NULL) {
        fprintf(stderr, "failed to connect to Wayland display\n");
        return -1;
    }
    display.registry = wl_display_get_registry(display.display);
    wl_registry_add_listener(display.registry, &registry_listener, &display);
    wl_display_roundtrip(display.display);

    init_egl(&display);
    create_window(&window);
    init_gl();

    struct timeval tv0;
    gettimeofday(&tv0, NULL);
    double t0 = tv0.tv_sec + tv0.tv_usec / 1000000.0;
    double t_last = t0;
    int frames = 0;

    while (wl_display_dispatch(display.display) != -1) {
        struct timeval tv;
        gettimeofday(&tv, NULL);
        double t = tv.tv_sec + tv.tv_usec / 1000000.0;
        double dt = t - t_last;
        t_last = t;

        angle += 70.0 * dt;
        if (angle > 3600.0)
           angle -= 3600.0;

        if (window.configured)
           redraw(&window);

        frames++;
        if (t - t0 >= 5.0) {
            GLfloat seconds = t - t0;
            printf("%d frames in %.1f seconds = %.3f FPS\n", frames, seconds, frames / seconds);
            t0 = t;
            frames = 0;
        }
    }

    return 0;
}
